<?php
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/excel.php';
if(getenv('CV_TEST_DATABASE')!=='yes')die("Usa una base de datos de pruebas y define CV_TEST_DATABASE=yes.\n");
function check(bool $ok,string $label): void {if(!$ok)throw new RuntimeException('FALLÓ: '.$label);echo "OK: $label\n";}
$pdo=db();$pdo->beginTransaction();$temp=tempnam(sys_get_temp_dir(),'cv-test');
try{
 execute('INSERT INTO vehicles(brand,model,plates,economic_number,responsible,baseline_date,baseline_km) VALUES (?,?,?,?,?,?,?)',['Nissan','Versa','TEST-'.substr(keygen(),0,12),'TEST-'.substr(keygen(),0,8),'Ana López','2026-08-01','100']);$vid=(int)$pdo->lastInsertId();$v=need('vehicles',$vid);
 $a=['vehicle_id'=>$vid,'request_date'=>'2026-08-31','departure_at'=>'2026-08-31 09:00:00','arrival_at'=>'2026-08-31 10:00:00','km_start'=>'100.00','km_end'=>'150.00','driver'=>'Ana López','purpose'=>'Entrega de documentación'];$k1=keygen();$id1=createTrip($a,$k1);
 $b=$a;$b['request_date']='2026-09-01';$b['departure_at']='2026-09-01 09:00:00';$b['arrival_at']='2026-09-01 11:00:00';$b['km_start']='150.00';$b['km_end']='180.00';$k2=keygen();$id2=createTrip($b,$k2);
 createFuel($id2,['fuel_date'=>'2026-09-01','liters'=>'10.125','amount'=>'250.50','card_last4'=>'0007'],keygen());createFuel($id2,['fuel_date'=>'2026-09-01','liters'=>'5.000','amount'=>'120.00','card_last4'=>'0234'],keygen());createFuel($id2,['fuel_date'=>'2026-10-01','liters'=>'7.000','amount'=>'170.00','card_last4'=>'0007'],keygen());
 $summary=monthSummary($v,'2026-09');check($summary['initial']===150.0&&$summary['final']===180.0&&$summary['km']===30.0,'Lecturas mensuales y km no duplicados por gasolina');check($summary['liters']===15.125&&$summary['amount']===370.5,'Múltiples cargas sumadas una sola vez');check(monthSummary($v,'2026-10')['liters']===7.0,'Carga de otro mes contabilizada correctamente');
 Xlsx::write($temp,dataSheets(null,$vid));$batch=parseImport($temp);check(count($batch['trips'])===2&&count($batch['fuel'])===3,'XLSX exportado se puede reimportar');check($batch['fuel'][0]['data']['card_last4']==='0007','XLSX conserva ceros de tarjeta');$preview=evaluateImport($batch);check($preview['trips']===0&&$preview['fuel']===0&&$preview['skipped']===5,'Reimportación idempotente');
 $batch['trips'][0]['data']['driver']='Otra persona';$rejected=false;try{evaluateImport($batch);}catch(RuntimeException){$rejected=true;}check($rejected,'Clave existente con cambios se rechaza');
 $newKey=keygen();$c=$b;$c['departure_at']='2026-09-02 09:00:00';$c['arrival_at']='2026-09-02 10:00:00';$c['request_date']='2026-09-02';$c['km_start']='180.00';$c['km_end']='200.00';$batch=['trips'=>[['key'=>$newKey,'row'=>2,'data'=>$c]],'fuel'=>[['key'=>keygen(),'trip_key'=>$newKey,'row'=>2,'data'=>['fuel_date'=>'2026-09-02','liters'=>'2.500','amount'=>'60.00','card_last4'=>'0001']]]];$preview=evaluateImport($batch);check($preview['warnings']===[]&&$preview['trips']===1,'Previsualización de lote nuevo sin escritura');check(row('SELECT id FROM trips WHERE reference_key=?',[$newKey])===null,'Revisión no inserta datos');evaluateImport($batch,true);$created=row('SELECT * FROM trips WHERE reference_key=?',[$newKey]);check($created!==null&&row('SELECT COUNT(*) n FROM fuel_loads WHERE trip_id=?',[$created['id']])['n']===1,'Importación guarda relaciones de cargas nuevas');
 execute('DELETE FROM trips WHERE id=?',[$created['id']]);check(row('SELECT COUNT(*) n FROM fuel_loads WHERE trip_id=?',[$created['id']])['n']===0,'Eliminar bitácora elimina sus cargas');
 check(count(rows('SELECT * FROM suggestions WHERE kind=? AND value=?',['driver','Ana López']))===1,'Autocompletado independiente sin duplicados');
 $formulaSheets=[['name'=>'Bitacoras','rows'=>[TRIP_HEADERS,[$k1,$v['economic_number'],'2026-08-31','09:00','10:00',['formula'=>'1+1','value'=>2],150,'Ana','Entrega']]]];Xlsx::write($temp,$formulaSheets);$rejected=false;try{parseImport($temp);}catch(RuntimeException){$rejected=true;}check($rejected,'Importación rechaza fórmulas');
 echo "Todas las pruebas de integración pasaron; cambios revertidos.\n";
}finally{$pdo->rollBack();unlink($temp);}
