<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
session_set_cookie_params(['httponly'=>true,'samesite'=>'Lax','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off']);session_start();
header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: same-origin');header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");header('Cache-Control: no-store');
$_SESSION['csrf']??=keygen();$page=(string)($_GET['page']??'dashboard');$error='';$warnings=[];$warningPayload=[];$importPreview=null;
if(empty($_SESSION['authenticated'])){
 $page='login';
 if($_SERVER['REQUEST_METHOD']==='POST')try{checkCsrf();$mode=(string)($_POST['auth_action']??'login');if($mode==='register'){$username=textValue($_POST['username']??'','Usuario',80);$password=(string)($_POST['password']??'');if(strlen($password)<6)throw new RuntimeException('La contraseña debe tener al menos 6 caracteres.');$name=textValue($_POST['driver_name']??'','Nombre del conductor',150);$lic=textValue($_POST['license_number']??'','Número de licencia',80);$exp=dateValue($_POST['license_expires']??'','Vencimiento');execute('INSERT INTO users(username,password_hash,driver_name,license_number,license_expires) VALUES (?,?,?,?,?)',[$username,password_hash($password,PASSWORD_DEFAULT),$name,$lic,$exp]);session_regenerate_id(true);$_SESSION['authenticated']=true;$_SESSION['role']='user';$_SESSION['user_id']=(int)db()->lastInsertId();$_SESSION['csrf']=keygen();redirect('dashboard');}
  $user=(string)($_POST['username']??'');$pass=(string)($_POST['password']??'');if(hash_equals(getenv('APP_USER')?:'admin',$user)&&hash_equals(getenv('APP_PASSWORD')?:'',$pass)){$_SESSION['authenticated']=true;$_SESSION['role']='admin';}else{$user=mb_strtoupper(trim($user),'UTF-8');$u=row('SELECT * FROM users WHERE username=? AND active=1',[$user]);if(!$u||!password_verify($pass,$u['password_hash']))throw new RuntimeException('Usuario o contraseña incorrectos.');$_SESSION['authenticated']=true;$_SESSION['role']='user';$_SESSION['user_id']=(int)$u['id'];}session_regenerate_id(true);$_SESSION['csrf']=keygen();redirect('dashboard');
 }catch(Throwable $e){$error=$e instanceof PDOException?'Ese nombre de usuario ya existe o no se pudo guardar la cuenta.':$e->getMessage();}
}else{
 require __DIR__.'/../app/excel.php';require __DIR__.'/../app/actions.php';
 if($page==='verification_status'&&isAdmin()&&$_SERVER['REQUEST_METHOD']==='GET'){header('Content-Type: application/json; charset=utf-8');echo json_encode(verificationResponseData(),JSON_UNESCAPED_UNICODE);exit;}
 try{if($_SERVER['REQUEST_METHOD']==='POST')handleAction();if($page==='export')exportExcel((string)($_GET['kind']??'general'),(string)($_GET['month']??date('Y-m')),(int)($_GET['vehicle_id']??0));}catch(Throwable $e){try{if(db()->inTransaction())db()->rollBack();}catch(Throwable $ignored){}if(($_SERVER['HTTP_X_REQUESTED_WITH']??'')==='XMLHttpRequest' && ($_POST['action']??'')==='verification_save'){http_response_code(422);header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>false,'error'=>$e instanceof PDOException?'No fue posible completar la operación en la base de datos.':$e->getMessage()],JSON_UNESCAPED_UNICODE);exit;}$error=$e instanceof PDOException?'No fue posible completar la operación en la base de datos.':$e->getMessage();}
}
require_once __DIR__.'/../app/views.php';renderHeader($page);if($error)echo '<div class="notice error">'.e($error).'</div>';if(isset($_SESSION['flash'])){echo '<div class="notice success">'.e($_SESSION['flash']).'</div>';unset($_SESSION['flash']);}
try{switch($page){case 'login':loginView();break;case 'dashboard':dashboardView();break;case 'vehicles':vehiclesView();break;case 'vehicle':vehicleView();break;case 'trip_form':tripFormView();break;case 'trip':tripView();break;case 'records':recordsView();break;case 'profile':profileView();break;case 'fuel':fuelView();break;case 'period':periodView();break;case 'reservations':reservationsView();break;case 'reservation_form':reservationFormView();break;case 'reports':reportsView();break;case 'gaps':gapsView();break;case 'import':importView();break;case 'users':usersView();break;case 'user_edit':userEditView();break;default:http_response_code(404);echo '<section class="panel"><h1>Página no encontrada</h1></section>';}}catch(Throwable $e){echo '<div class="notice error">'.e($e->getMessage()).'</div>';}
renderFooter();
