<?php
require_once __DIR__.'/verification_views.php';
function handleAction(): void {
 global $warnings,$warningPayload,$importPreview,$error;checkCsrf();$action=$_POST['action']??'';$id=(int)($_POST['id']??0);
 if($action==='logout'){$_SESSION=[];session_destroy();redirect('login');}
 if($action==='user_save'){requireAdmin();$uid=(int)($_POST['user_id']??0);$u=need('users',$uid);$username=textValue($_POST['username']??'','Usuario',80);$name=textValue($_POST['driver_name']??'','Nombre del conductor',150);$lic=textValue($_POST['license_number']??'','Número de licencia',80);$exp=dateValue($_POST['license_expires']??'','Vencimiento');$newPassword=(string)($_POST['password']??'');if($newPassword!==''&&strlen($newPassword)<6)throw new RuntimeException('La nueva contraseña debe tener al menos 6 caracteres.');if($newPassword!=='')execute('UPDATE users SET username=?,driver_name=?,license_number=?,license_expires=?,password_hash=? WHERE id=?',[$username,$name,$lic,$exp,password_hash($newPassword,PASSWORD_DEFAULT),$uid]);else execute('UPDATE users SET username=?,driver_name=?,license_number=?,license_expires=? WHERE id=?',[$username,$name,$lic,$exp,$uid]);flash('Cuenta de usuario actualizada.');redirect('users');}
 if($action==='user_delete_keep'){requireAdmin();$uid=(int)($_POST['user_id']??0);need('users',$uid);db()->beginTransaction();try{execute('UPDATE trips SET user_id=NULL WHERE user_id=?',[$uid]);execute('UPDATE reservations SET user_id=NULL WHERE user_id=?',[$uid]);execute('DELETE FROM users WHERE id=?',[$uid]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}flash('Cuenta eliminada; sus registros fueron conservados.');redirect('users');}
 if($action==='user_delete_all'){requireAdmin();$uid=(int)($_POST['user_id']??0);need('users',$uid);db()->beginTransaction();try{execute('DELETE FROM reservations WHERE user_id=?',[$uid]);execute('DELETE FROM trips WHERE user_id=?',[$uid]);execute('DELETE FROM users WHERE id=?',[$uid]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}flash('Cuenta y registros del usuario eliminados.');redirect('users');}
 if($action==='profile_save'){if(!isExternal())throw new RuntimeException('Sesión de usuario requerida.');$name=textValue($_POST['driver_name']??'','Nombre',150);$lic=textValue($_POST['license_number']??'','Número de licencia',80);$exp=dateValue($_POST['license_expires']??'','Vencimiento');execute('UPDATE users SET driver_name=?,license_number=?,license_expires=? WHERE id=?',[$name,$lic,$exp,currentUserId()]);flash('Perfil de conductor actualizado.');redirect('profile');}
 if($action==='reservation_save'){saveReservation($_POST,$id);flash($id?'Programación actualizada.':'Vehículo programado.');redirect('reservations');}
 if($action==='reservation_cancel'){cancelReservation($id,(int)($_POST['version']??0));flash('Programación eliminada.');redirect('reservations');}
 if($action==='verification_save'){requireAdmin();saveVerification($_POST);if(($_SERVER['HTTP_X_REQUESTED_WITH']??'')==='XMLHttpRequest'){header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true]+verificationResponseData(),JSON_UNESCAPED_UNICODE);exit;}flash('Verificación actualizada.');redirect('dashboard');}
 if($action==='vehicle_save'){requireAdmin();$v=['brand'=>textValue($_POST['brand']??'','Marca',80),'model'=>textValue($_POST['model']??'','Modelo',100),'model_year'=>(int)($_POST['model_year']??0),'plates'=>strtoupper(textValue($_POST['plates']??'','Placas',30)),'economic_number'=>textValue($_POST['economic_number']??'','No. económico',30),'responsible'=>textValue($_POST['responsible']??'','Responsable',150),'department'=>textValue($_POST['department']??'','Departamento',150),'baseline_date'=>dateValue($_POST['baseline_date']??'','Fecha de referencia'),'baseline_km'=>integerValue($_POST['baseline_km']??'','Km de referencia'),'verification_permit'=>!empty($_POST['verification_permit'])?1:0];if($v['model_year']<1900||$v['model_year']>2100)throw new RuntimeException('Año de modelo inválido.');if($id){execute('UPDATE vehicles SET brand=?,model=?,model_year=?,plates=?,economic_number=?,responsible=?,department=?,baseline_date=?,baseline_km=?,verification_permit=? WHERE id=?',[...array_values($v),$id]);}else{execute('INSERT INTO vehicles(brand,model,model_year,plates,economic_number,responsible,department,baseline_date,baseline_km,verification_permit) VALUES (?,?,?,?,?,?,?,?,?,?)',array_values($v));$id=(int)db()->lastInsertId();}flash('Vehículo guardado.');redirect('vehicle',['id'=>$id]);}
 if($action==='trip_save'){
  $pending=pendingTrip();$confirmPending=!empty($_POST['confirm_pending']);
  if($confirmPending&&$pending){
   if(!hash_equals((string)$pending['token'],(string)($_POST['warning_token']??'')))throw new RuntimeException('La confirmación de advertencias venció. Captura nuevamente la bitácora.');
   $id=(int)$pending['id'];$old=$id?need('trips',$id):null;if($old&&!canEditTrip($old))throw new RuntimeException('Solo puedes editar tus propios registros.');if(isExternal())assertLicenseValid();
   $t=$pending['data'];
  }else{
   clearPendingTrip();$old=$id?need('trips',$id):null;if($old&&!canEditTrip($old))throw new RuntimeException('Solo puedes editar tus propios registros.');if(isExternal())assertLicenseValid();$t=normalizeTripForm($_POST);if(isExternal()){$u=currentUser();$t['driver']=$u['driver_name'];}
  }
  $vehicle=need('vehicles',$t['vehicle_id']);$others=rows('SELECT * FROM trips WHERE vehicle_id=? AND id<>? ORDER BY departure_at,id',[$t['vehicle_id'],$id]);$blocking=tripBlockingConflicts($t,$others);if($blocking)throw new RuntimeException('No se puede registrar la bitácora por conflictos: '.implode(' ',$blocking));$periods=rows('SELECT * FROM inactive_periods WHERE vehicle_id=?',[$t['vehicle_id']]);if(isExternal()&&periodForDate($periods,$t['request_date']))throw new RuntimeException('No puedes registrar una bitácora: el vehículo está en un periodo de inactividad definido por el administrador.');$warnings=tripWarnings($t,$others,$vehicle,$periods);$warningPayload=[$t,$id];
  if($warnings){
   if($confirmPending && warningsConfirmed($warningPayload,$warnings)){
    clearPendingTrip();
   }else{
    storePendingTrip($t,$id,$warnings);
    redirect('trip_form',['id'=>$id,'vehicle_id'=>$t['vehicle_id'],'pending'=>1]);
   }
  }else{clearPendingTrip();}
  if($id){execute('UPDATE trips SET vehicle_id=?,request_date=?,departure_at=?,arrival_at=?,km_start=?,km_end=?,driver=?,purpose=?,requester=?,observations=?,version=version+1 WHERE id=?',[...array_values($t),$id]);remember($t);}else $id=createTrip($t,keygen(),isExternal()?currentUserId():null);flash('Bitácora #'.$id.' guardada.');redirect('trip',['id'=>$id]);
 }
 if($action==='trip_delete'){requireAdmin();$t=need('trips',$id);execute('DELETE FROM trips WHERE id=?',[$id]);flash('Bitácora eliminada.');redirect('vehicle',['id'=>$t['vehicle_id']]);}
 if($action==='fuel_save'||$action==='fuel_delete'){requireAdmin();if($action==='fuel_delete'){execute('DELETE FROM fuel_loads WHERE id=?',[$id]);flash('Carga eliminada.');redirect('fuel');}$f=normalizeFuel($_POST);if($id)execute('UPDATE fuel_loads SET vehicle_id=?,fuel_date=?,liters=?,amount=?,payment_method=?,card_last5=?,version=version+1 WHERE id=?',[...array_values($f),$id]);else createFuel($f,keygen());flash('Carga de gasolina guardada.');redirect('fuel');}
 if($action==='period_save'||$action==='period_delete'){requireAdmin();$vid=(int)($_POST['vehicle_id']??0);if($action==='period_delete'){execute('DELETE FROM inactive_periods WHERE id=?',[$id]);flash('Periodo eliminado.');redirect('vehicle',['id'=>$vid]);}$a=dateValue($_POST['start_date']??'','Inicio');$b=trim($_POST['end_date']??'')!==''?dateValue($_POST['end_date'],'Fin'):null;$reason=$_POST['reason']??'';if(!in_array($reason,['DESCOMPUESTO Y EN LAS INSTALACIONES DEL IMPLAN','RECIBIENDO SERVICIO EN EL TALLER MECÁNICO','NO DISPONIBLE'],true))throw new RuntimeException('Estado inválido.');if($id)execute('UPDATE inactive_periods SET start_date=?,end_date=?,reason=?,notes=?,version=version+1 WHERE id=?',[$a,$b,$reason,mb_strtoupper(trim((string)$_POST['notes']),'UTF-8'),$id]);else execute('INSERT INTO inactive_periods(vehicle_id,start_date,end_date,reason,notes) VALUES (?,?,?,?,?)',[$vid,$a,$b,$reason,mb_strtoupper(trim((string)$_POST['notes']),'UTF-8')]);flash('Periodo guardado.');redirect('vehicle',['id'=>$vid]);}
 if($action==='import_preview'){requireAdmin();$file=$_FILES['xlsx']??null;if(!$file||$file['error']!==UPLOAD_ERR_OK)throw new RuntimeException('No se recibió el XLSX.');$batch=parseImport($file['tmp_name']);$importPreview=evaluateImport($batch);$_SESSION['import_batch']=$batch;$_SESSION['import_review']=$importPreview;return;}
 if($action==='import_commit'){requireAdmin();$batch=$_SESSION['import_batch']??null;if(!$batch)throw new RuntimeException('Primero revisa un archivo.');$result=evaluateImport($batch,true);unset($_SESSION['import_batch'],$_SESSION['import_review']);flash('Importación completa: '.$result['trips'].' bitácoras y '.$result['fuel'].' cargas.');redirect('import');}
 throw new RuntimeException('Acción no encontrada.');
}
