<?php
declare(strict_types=1);
final class TemplateXlsx {
 private static function sheetPath(ZipArchive $z,string $sheet): string {
  $wb=new DOMDocument();$wb->loadXML($z->getFromName('xl/workbook.xml'));$xp=new DOMXPath($wb);$xp->registerNamespace('m','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$xp->registerNamespace('r','http://schemas.openxmlformats.org/officeDocument/2006/relationships');
  $rid='';foreach($xp->query('//m:sheets/m:sheet') as $n)if($n->getAttribute('name')===$sheet){$rid=$n->getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');break;}if(!$rid)throw new RuntimeException('No se encontró la hoja '.$sheet.' en la plantilla.');
  $rels=new DOMDocument();$rels->loadXML($z->getFromName('xl/_rels/workbook.xml.rels'));foreach($rels->documentElement->childNodes as $n)if($n instanceof DOMElement&&$n->getAttribute('Id')===$rid){$t=$n->getAttribute('Target');return str_starts_with($t,'/')?ltrim($t,'/'):'xl/'.$t;}throw new RuntimeException('No se encontró la relación de la hoja.');
 }
 private static function excelSerial(string $date): float { $d=new DateTimeImmutable($date.' 00:00:00'); $base=new DateTimeImmutable('1899-12-30 00:00:00'); return (float)$base->diff($d)->days; }
 private static function setDateCell(DOMDocument $doc,string $ref,string $date): void { $ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main'; preg_match('/([A-Z]+)(\d+)/',$ref,$m); $rowNo=$m[2]; $xp=new DOMXPath($doc); $xp->registerNamespace('m',$ns); $row=$xp->query('//m:sheetData/m:row[@r="'.$rowNo.'"]')->item(0); if(!$row){$row=$doc->createElementNS($ns,'row');$row->setAttribute('r',$rowNo);$xp->query('//m:sheetData')->item(0)->appendChild($row);} $cell=$xp->query('m:c[@r="'.$ref.'"]',$row)->item(0); if(!$cell){$cell=$doc->createElementNS($ns,'c');$cell->setAttribute('r',$ref);$row->appendChild($cell);} while($cell->firstChild)$cell->removeChild($cell->firstChild); $cell->removeAttribute('t'); $v=$doc->createElementNS($ns,'v');$v->appendChild($doc->createTextNode((string)self::excelSerial($date)));$cell->appendChild($v); }
 private static function setCell(DOMDocument $doc,string $ref,mixed $value): void {
  $ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';preg_match('/([A-Z]+)(\d+)/',$ref,$m);$rowNo=$m[2];$xp=new DOMXPath($doc);$xp->registerNamespace('m',$ns);$row=$xp->query('//m:sheetData/m:row[@r="'.$rowNo.'"]')->item(0);if(!$row){$row=$doc->createElementNS($ns,'row');$row->setAttribute('r',$rowNo);$xp->query('//m:sheetData')->item(0)->appendChild($row);} $cell=$xp->query('m:c[@r="'.$ref.'"]',$row)->item(0);if(!$cell){$cell=$doc->createElementNS($ns,'c');$cell->setAttribute('r',$ref);$row->appendChild($cell);}while($cell->firstChild)$cell->removeChild($cell->firstChild);
  if(is_int($value)||is_float($value)){$cell->removeAttribute('t');$v=$doc->createElementNS($ns,'v',(string)$value);$cell->appendChild($v);}else{$cell->setAttribute('t','inlineStr');$is=$doc->createElementNS($ns,'is');$t=$doc->createElementNS($ns,'t');$t->setAttribute('xml:space','preserve');$t->appendChild($doc->createTextNode((string)$value));$is->appendChild($t);$cell->appendChild($is);}
 }
 public static function download(string $template,string $sheet,array $cells,string $filename): never {
  $tmp=tempnam(sys_get_temp_dir(),'cv-template-').'.xlsx';copy($template,$tmp);$z=new ZipArchive();if($z->open($tmp)!==true)throw new RuntimeException('No se pudo abrir la plantilla XLSX.');$path=self::sheetPath($z,$sheet);$xml=$z->getFromName($path);$doc=new DOMDocument();$doc->preserveWhiteSpace=false;$doc->formatOutput=false;if(!$doc->loadXML($xml))throw new RuntimeException('La plantilla contiene XML inválido.');foreach($cells as $ref=>$value){ if(is_array($value)&&isset($value['excel_date'])) self::setDateCell($doc,$ref,(string)$value['excel_date']); else self::setCell($doc,$ref,$value); }$z->addFromString($path,$doc->saveXML());$z->close();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Content-Length: '.filesize($tmp));header('Cache-Control: no-store');readfile($tmp);unlink($tmp);exit;
 }
}
