<?php
function renderHeader(string $page): void {
 $titles=['dashboard'=>'Panel de vehículos','vehicles'=>'Vehículos','vehicle'=>'Ficha de vehículo','trip_form'=>'Registro de bitácora','trip'=>'Detalle de bitácora','fuel'=>'Carga de gasolina','period'=>'Periodo de inactividad','reservations'=>'Programación','reservation_form'=>'Apartar vehículo','reports'=>'Concentrados','gaps'=>'Kilómetros pendientes','import'=>'Importar registros','login'=>'Acceso'];
?><!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($titles[$page]??'Control vehicular')?> · Control vehicular</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/app.css"><script src="assets/app.js" defer></script></head><body>
<?php if($page!=='login'):?><aside class="sidebar"><a class="brand" href="<?=e(url('dashboard'))?>"><span class="brand-mark">CV</span><span>Control<br><strong>vehicular</strong></span></a><div class="nav-caption">ADMINISTRACIÓN</div><nav><?php foreach(['dashboard'=>['Panel de vehículos','◫'],'vehicles'=>['Vehículos','▣'],'reservations'=>['Programación','▦'],'reports'=>['Concentrados','▤'],'gaps'=>['Kilómetros pendientes','↔'],'import'=>['Importar registros','↥']] as $p=>$n):?><a class="<?=$page===$p?'active':''?>" href="<?=e(url($p))?>"><span aria-hidden="true"><?=e($n[1])?></span><?=e($n[0])?></a><?php endforeach;?></nav><div class="side-bottom"><span>Bitácoras y combustible</span><small>Versión 1.1</small><form method="post"><?=csrf()?><input type="hidden" name="action" value="logout"><button class="logout">Cerrar sesión</button></form></div></aside><?php endif;?>
<div class="shell <?=$page==='login'?'login-shell':''?>"><?php if($page!=='login'):?><header class="topbar"><span>GESTIÓN DE FLOTA</span><div class="topbar-actions"><span><?=e(date('d/m/Y'))?></span><form method="post" class="mobile-logout"><?=csrf()?><input type="hidden" name="action" value="logout"><button class="button secondary small">Salir</button></form></div></header><?php endif;?><main id="main">
<?php }
function renderFooter(): void {echo '</main><footer class="footer">Control vehicular · Registro y seguimiento de recorridos</footer></div></body></html>';}
function pageTitle(string $title,string $sub='',string $action=''): void {echo '<div class="page-title"><div><h1>'.e($title).'</h1>'.($sub?'<p>'.e($sub).'</p>':'').'</div>'.$action.'</div>';}
function linkButton(string $text,string $page,array $p=[],string $class=''): string {return '<a class="button '.e($class).'" href="'.e(url($page,$p)).'">'.e($text).'</a>';}
function inputField(string $name,string $label,mixed $value='',string $type='text',string $attrs=''): void {echo '<label class="field"><span>'.e($label).'</span><input name="'.e($name).'" type="'.e($type).'" value="'.e($value).'" '.$attrs.'></label>';}
function hidden(string $name,mixed $value): void {echo '<input type="hidden" name="'.e($name).'" value="'.e($value).'">';}
function vehicleSelect(mixed $selected=0,bool $all=false): void {echo '<label class="field"><span>Vehículo</span><select name="vehicle_id" '.(!$all?'required':'').'>';if($all)echo '<option value="0">Todos los vehículos</option>';else echo '<option value="">Selecciona un vehículo</option>';foreach(rows('SELECT * FROM vehicles ORDER BY economic_number') as $v)echo '<option value="'.$v['id'].'" '.((int)$selected===(int)$v['id']?'selected':'').'>'.e($v['economic_number'].' · '.$v['brand'].' '.$v['model'].' · '.$v['plates']).'</option>';echo '</select></label>';}
function warningBox(): void {global $warnings,$warningPayload;if(!$warnings)return;echo '<div class="notice warning"><strong>Revisa antes de guardar</strong><ul>';foreach($warnings as $w)echo '<li>'.e($w).'</li>';echo '</ul><label class="check"><input type="checkbox" name="accept_warnings" value="1" required> He revisado las advertencias y deseo guardar.</label>';hidden('warning_token',warningToken($warningPayload,$warnings));echo '</div>';}
function deleteForm(string $action,int $id,string $message,array $extra=[],string $label='Eliminar'): void {echo '<form method="post" class="inline" data-confirm="'.e($message).'">'.csrf();hidden('action',$action);hidden('id',$id);foreach($extra as $k=>$v)hidden($k,$v);echo '<button class="button danger small" type="submit">'.e($label).'</button></form>';}
function loginView(): void {pageTitle('Control vehicular','Accede para registrar y consultar las bitácoras.');echo '<form method="post" class="panel login-card">'.csrf();inputField('username','Usuario','','text','autocomplete="username" required');inputField('password','Contraseña','','password','autocomplete="current-password" required');echo '<button class="button">Entrar</button></form>';}
function dashboardView(): void {
 pageTitle('Panel de vehículos','Selecciona un vehículo para registrar un recorrido.',linkButton('+ Nuevo vehículo','vehicle'));
 $vehicles=rows('SELECT * FROM vehicles ORDER BY economic_number');$periods=rows('SELECT * FROM inactive_periods ORDER BY start_date');$today=date('Y-m-d');[$start,$end]=monthBounds(date('Y-m'));
 $stat=row('SELECT COUNT(*) n,COALESCE(SUM(km_end-km_start),0) km FROM trips WHERE departure_at>=? AND departure_at<?',[$start,$end]);$fuel=row('SELECT COALESCE(SUM(liters),0) liters,COALESCE(SUM(amount),0) amount FROM fuel_loads WHERE fuel_date>=? AND fuel_date<?',[$start,$end]);$available=0;foreach($vehicles as $v)if(!periodForDate(array_filter($periods,fn($p)=>$p['vehicle_id']==$v['id']),$today))$available++;
 echo '<section class="stats" aria-label="Resumen del mes"><div><span>Disponibles hoy</span><strong>'.$available.' <small>/ '.count($vehicles).'</small></strong></div><div><span>Km registrados · '.e(date('m/Y')).'</span><strong>'.num($stat['km']).'</strong></div><div><span>Gasolina del mes</span><strong>'.num($fuel['liters'],3).' <small>L</small></strong></div><div><span>Pagado este mes</span><strong>$'.num($fuel['amount']).'</strong></div></section>';
 echo '<div class="section-heading"><h2>Flota</h2><span>'.count($vehicles).' vehículos</span></div><section class="vehicle-grid">';
 if(!$vehicles)echo '<div class="panel empty"><h2>Registra tu primer vehículo</h2><p>Agrega sus placas, responsable y una lectura de kilometraje de referencia.</p>'.linkButton('Agregar vehículo','vehicle').'</div>';
 foreach($vehicles as $v){$state=periodForDate(array_filter($periods,fn($p)=>$p['vehicle_id']==$v['id']),$today);$last=row('SELECT km_end FROM trips WHERE vehicle_id=? ORDER BY departure_at DESC,id DESC LIMIT 1',[$v['id']]);echo '<a class="vehicle-card '.($state?'inactive':'').'" href="'.e(url('trip_form',['vehicle_id'=>$v['id']])).'"><div class="card-top"><span class="economic">'.e($v['economic_number']).'</span><span class="badge '.($state?'amber':'green').'">'.e($state['reason']??'Disponible').'</span></div><h3>'.e($v['brand'].' '.$v['model']).'</h3><div class="plate">'.e($v['plates']).'</div><p>'.e($v['responsible']).'</p><div class="card-bottom"><span>'.num($last['km_end']??$v['baseline_km']).' km <small>última lectura</small></span><strong>Registrar <span aria-hidden="true">↗</span></strong></div></a>';}
 echo '</section><section class="panel search-panel"><div class="section-heading"><h2>Buscar bitácoras</h2><span>Consulta, edita o agrega gasolina</span></div>';
 $q=trim((string)($_GET['q']??''));$vid=(int)($_GET['vehicle_id']??0);$month=trim((string)($_GET['month']??''));
 echo '<form method="get" class="search-form">';hidden('page','dashboard');inputField('q','ID, fecha, kilómetro o conductor',$q,'search','placeholder="Ej. 24, 2026-09-15, 45200 o Ana"');vehicleSelect($vid,true);inputField('month','Mes de salida',$month,'month');echo '<button class="button" type="submit">Buscar</button><a class="text-link" href="'.e(url('dashboard')).'">Limpiar</a></form>';
 $where=[];$args=[];if($vid){$where[]='t.vehicle_id=?';$args[]=$vid;}if($month){[$a,$b]=monthBounds($month);$where[]='t.departure_at>=? AND t.departure_at<?';array_push($args,$a,$b);}if($q!==''){$clauses=['t.driver LIKE ?','t.purpose LIKE ?','v.brand LIKE ?','v.model LIKE ?','v.plates LIKE ?','v.economic_number LIKE ?'];$like='%'.str_replace(['!','%','_'],['!!','!%','!_'],$q).'%';$clauses=array_map(fn($c)=>$c." ESCAPE '!'",$clauses);array_push($args,$like,$like,$like,$like,$like,$like);if(ctype_digit(ltrim($q,'#'))){$clauses[]='t.id=?';$args[]=(int)ltrim($q,'#');}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$q)){$clauses[]='(t.request_date=? OR DATE(t.departure_at)=? OR DATE(t.arrival_at)=?)';array_push($args,$q,$q,$q);}if(is_numeric($q)){$clauses[]='(t.km_start<=? AND t.km_end>=?)';array_push($args,$q,$q);}$where[]='('.implode(' OR ',$clauses).')';}
 $from=' FROM trips t JOIN vehicles v ON v.id=t.vehicle_id'.($where?' WHERE '.implode(' AND ',$where):'');$count=(int)row('SELECT COUNT(*) n'.$from,$args)['n'];$pn=max(1,min((int)($_GET['p']??1),max(1,(int)ceil($count/25))));$data=rows('SELECT t.*,v.economic_number,v.plates'.$from.' ORDER BY t.departure_at DESC,t.id DESC LIMIT 25 OFFSET '.(($pn-1)*25),$args);tripTable($data);
 echo '<div class="pagination"><span>'.$count.' registros · Página '.$pn.' de '.max(1,(int)ceil($count/25)).'</span><div>';if($pn>1)echo linkButton('Anterior','dashboard',['q'=>$q,'month'=>$month,'vehicle_id'=>$vid,'p'=>$pn-1],'secondary small');if($pn*25<$count)echo linkButton('Siguiente','dashboard',['q'=>$q,'month'=>$month,'vehicle_id'=>$vid,'p'=>$pn+1],'secondary small');echo '</div></div></section>';
}
function tripTable(array $data): void {echo '<div class="table-wrap"><table><thead><tr><th>ID</th><th>Vehículo</th><th>Salida</th><th>Llegada</th><th>Conductor</th><th>Km inicial</th><th>Km final</th><th>Recorridos</th><th>Acciones</th></tr></thead><tbody>';foreach($data as $t){echo '<tr><td><a class="id-link" href="'.e(url('trip',['id'=>$t['id']])).'">#'.$t['id'].'</a></td><td>'.e($t['economic_number']??'').'<small>'.e($t['plates']??'').'</small></td><td>'.e(substr($t['departure_at'],0,16)).'</td><td>'.e(substr($t['arrival_at'],0,16)).'</td><td>'.e($t['driver']).'</td><td>'.num($t['km_start']).'</td><td>'.num($t['km_end']).'</td><td><strong>'.num($t['km_end']-$t['km_start']).'</strong></td><td><div class="actions">'.linkButton('Ver / gasolina','trip',['id'=>$t['id']],'secondary small').linkButton('Editar','trip_form',['id'=>$t['id']],'secondary small');deleteForm('trip_delete',(int)$t['id'],'¿Eliminar la bitácora #'.$t['id'].' y TODAS sus cargas de gasolina?',['version'=>$t['version']]);echo '</div></td></tr>';}
 if(!$data)echo '<tr><td colspan="9" class="empty">No hay bitácoras para esta consulta.</td></tr>';echo '</tbody></table></div>';}
function vehiclesView(): void {pageTitle('Vehículos','Datos de la flota e historial de disponibilidad.',linkButton('+ Nuevo vehículo','vehicle'));$vs=rows('SELECT * FROM vehicles ORDER BY economic_number');echo '<section class="panel table-wrap"><table><thead><tr><th>No. económico</th><th>Vehículo</th><th>Placas</th><th>Responsable</th><th>Estado hoy</th><th>Gestionar</th></tr></thead><tbody>';foreach($vs as $v){$p=periodForDate(rows('SELECT * FROM inactive_periods WHERE vehicle_id=?',[$v['id']]),date('Y-m-d'));echo '<tr><td>'.e($v['economic_number']).'</td><td>'.e($v['brand'].' '.$v['model']).'</td><td>'.e($v['plates']).'</td><td>'.e($v['responsible']).'</td><td><span class="badge '.($p?'amber':'green').'">'.e($p['reason']??'Disponible').'</span></td><td>'.linkButton('Editar / periodos','vehicle',['id'=>$v['id']],'secondary small').'</td></tr>';}if(!$vs)echo '<tr><td colspan="6" class="empty">Todavía no hay vehículos.</td></tr>';echo '</tbody></table></section>';}
function vehicleView(): void {
 $id=(int)($_GET['id']??0);$old=$id?need('vehicles',$id):[];$v=$_SERVER['REQUEST_METHOD']==='POST'?$_POST:$old;
 pageTitle($id?'Vehículo '.$old['economic_number']:'Nuevo vehículo','La lectura de referencia permite detectar los primeros kilómetros pendientes.',linkButton('Volver','vehicles',[],'secondary'));
 echo '<form method="post" class="panel">'.csrf();hidden('action','vehicle_save');hidden('id',$id);hidden('vehicle_version',$_POST['vehicle_version']??hash('sha256',json_encode($old)));echo '<div class="form-grid">';foreach(['brand'=>'Marca','model'=>'Modelo','plates'=>'Placas','economic_number'=>'No. económico','responsible'=>'Persona responsable'] as $f=>$label)inputField($f,$label,$v[$f]??'','text','required maxlength="'.(['brand'=>80,'model'=>100,'plates'=>30,'economic_number'=>30,'responsible'=>150][$f]).'"');inputField('baseline_date','Fecha de lectura de referencia',$v['baseline_date']??date('Y-m-d'),'date','required');inputField('baseline_km','Km de referencia',$v['baseline_km']??'','number','required min="0" step="0.01"');echo '</div><p class="help">Para importar históricos, utiliza una lectura anterior o igual al primer recorrido que registrarás. Si el vehículo ya tiene historial, cambiar la referencia modifica el cálculo de faltantes.</p><button class="button">Guardar vehículo</button></form>';
 if($id){echo '<section class="panel"><div class="section-heading"><h2>Periodos de inactividad</h2>'.linkButton('+ Registrar periodo','period',['vehicle_id'=>$id]).'</div><p class="help">Inicio y fin incluidos. Deja el fin vacío si sigue inactivo. Para reactivar hoy, termina el periodo ayer; el historial se conserva.</p><div class="table-wrap"><table><thead><tr><th>ID</th><th>Desde</th><th>Hasta</th><th>Motivo</th><th>Notas</th><th>Acciones</th></tr></thead><tbody>';
 foreach(rows('SELECT * FROM inactive_periods WHERE vehicle_id=? ORDER BY start_date DESC',[$id]) as $p){echo '<tr><td>#'.$p['id'].'</td><td>'.e($p['start_date']).'</td><td>'.e($p['end_date']??'Sin fecha de fin').'</td><td>'.e($p['reason']).'</td><td>'.e($p['notes']).'</td><td><div class="actions">'.linkButton('Editar / cerrar','period',['id'=>$p['id'],'vehicle_id'=>$id],'secondary small');deleteForm('period_delete',(int)$p['id'],'¿Eliminar este periodo del historial?',['vehicle_id'=>$id,'version'=>$p['version']]);echo '</div></td></tr>';}
 echo '</tbody></table></div></section><section class="panel"><h2>Eliminar vehículo</h2><p>Solo se permite si no tiene bitácoras ni periodos. Para retirar un vehículo con historial, crea un periodo sin fecha de fin.</p>';deleteForm('vehicle_delete',$id,'¿Eliminar este vehículo?');echo '</section>';}
}
function tripFormView(): void {
 $id=(int)($_GET['id']??0);$old=$id?need('trips',$id):[];$v=$old;
 if($id){$v['departure_date']=substr($old['departure_at'],0,10);$v['departure_time']=substr($old['departure_at'],11,5);$v['arrival_date']=substr($old['arrival_at'],0,10);$v['arrival_time']=substr($old['arrival_at'],11,5);}
 else{$vid=(int)($_GET['vehicle_id']??0);$last=$vid?row('SELECT km_end FROM trips WHERE vehicle_id=? ORDER BY departure_at DESC,id DESC LIMIT 1',[$vid]):null;$vehicle=$vid?need('vehicles',$vid):null;$v=['vehicle_id'=>$vid,'request_date'=>date('Y-m-d'),'departure_date'=>date('Y-m-d'),'arrival_date'=>date('Y-m-d'),'km_start'=>$last['km_end']??($vehicle['baseline_km']??'')];}
 if($_SERVER['REQUEST_METHOD']==='POST')$v=$_POST;
 pageTitle($id?'Editar bitácora #'.$id:'Nueva bitácora','Los kilómetros recorridos se calculan automáticamente.',linkButton('Volver',$id?'trip':'dashboard',$id?['id'=>$id]:[],'secondary'));
 echo '<form method="post" class="panel" id="trip-form">'.csrf();hidden('action','trip_save');hidden('id',$id);hidden('version',$v['version']??1);warningBox();echo '<div class="form-grid">';vehicleSelect($v['vehicle_id']??0);
 inputField('request_date','Fecha de solicitud',$v['request_date']??'','date','required');echo '</div><h2 class="form-section">Recorrido</h2><div class="form-grid">';inputField('departure_date','Fecha de salida',$v['departure_date']??'','date','required');inputField('departure_time','Hora de salida',$v['departure_time']??'','time','required');inputField('arrival_date','Fecha de llegada',$v['arrival_date']??'','date','required');inputField('arrival_time','Hora de llegada',$v['arrival_time']??'','time','required');inputField('km_start','Km iniciales',$v['km_start']??'','number','required min="0" step="0.01"');inputField('km_end','Km finales',$v['km_end']??'','number','required min="0" step="0.01"');echo '<div class="field"><span>Km recorridos</span><output id="km-distance">—</output></div></div><p class="help">El valor inicial sugerido es la última lectura registrada. Ajústalo si estás capturando un recorrido anterior.</p><div class="form-grid">';inputField('driver','Nombre del conductor',$v['driver']??'','text','required maxlength="150" list="driver-options" data-suggest="driver" autocomplete="off"');inputField('purpose','Comisión',$v['purpose']??'','text','required maxlength="500" list="purpose-options" data-suggest="purpose" autocomplete="off"');echo '<datalist id="driver-options"></datalist><datalist id="purpose-options"></datalist></div>';
 if(!$id){echo '<h2 class="form-section">Gasolina <span class="subtle">opcional</span></h2><label class="check"><input type="checkbox" name="add_fuel" id="add-fuel" value="1" '.(!empty($v['add_fuel'])?'checked':'').'> Agregar una carga junto con esta bitácora</label><div id="initial-fuel" class="form-grid">';fuelFields($v,false);echo '</div><p class="help">Puedes agregar más cargas desde el detalle, incluso después de registrar la bitácora.</p>';}
 echo '<div class="form-actions"><button class="button">'.(!empty($GLOBALS['warnings'])?'Confirmar y guardar':'Revisar y guardar').'</button></div></form>';
}
function fuelFields(array $v,bool $required=true): void {$r=$required?'required ':'';inputField('fuel_date','Fecha de carga',$v['fuel_date']??date('Y-m-d'),'date',$r);inputField('liters','Litros',$v['liters']??'','number',$r.'min="0.001" step="0.001"');inputField('amount','Importe total pagado (MXN)',$v['amount']??'','number',$r.'min="0" step="0.01"');inputField('card_last4','Últimos 4 dígitos de tarjeta',$v['card_last4']??'','text',$r.'inputmode="numeric" pattern="[0-9]{4}" minlength="4" maxlength="4" placeholder="0000"');}
function tripView(): void {
 $id=(int)($_GET['id']??0);$t=need('trips',$id);$v=need('vehicles',(int)$t['vehicle_id']);$fuels=rows('SELECT * FROM fuel_loads WHERE trip_id=? ORDER BY fuel_date,id',[$id]);
 pageTitle('Bitácora #'.$id,$v['economic_number'].' · '.$v['brand'].' '.$v['model'].' · '.$v['plates'],linkButton('Editar bitácora','trip_form',['id'=>$id]));
 $w=tripWarnings($t,rows('SELECT * FROM trips WHERE vehicle_id=? AND id<>? ORDER BY departure_at,id',[$t['vehicle_id'],$id]),$v,rows('SELECT * FROM inactive_periods WHERE vehicle_id=?',[$t['vehicle_id']]));if($w){echo '<details class="notice warning"><summary>'.count($w).' advertencia(s) en el historial actual</summary><ul>';foreach($w as $msg)echo '<li>'.e($msg).'</li>';echo '</ul></details>';}
 echo '<section class="panel"><dl class="detail-grid">';foreach(['Solicitud'=>$t['request_date'],'Salida'=>$t['departure_at'],'Llegada'=>$t['arrival_at'],'Conductor'=>$t['driver'],'Comisión'=>$t['purpose'],'Km iniciales'=>num($t['km_start']),'Km finales'=>num($t['km_end']),'Km recorridos'=>num($t['km_end']-$t['km_start'])] as $k=>$val)echo '<div><dt>'.e($k).'</dt><dd>'.e($val).'</dd></div>';echo '</dl><p class="help">Clave de importación: <code>'.e($t['reference_key']).'</code></p></section>';
 echo '<section class="panel"><div class="section-heading"><h2>Cargas de gasolina</h2>'.linkButton('+ Agregar carga','fuel',['trip_id'=>$id]).'</div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Fecha</th><th>Litros</th><th>Importe MXN</th><th>Tarjeta</th><th>Acciones</th></tr></thead><tbody>';
 foreach($fuels as $f){echo '<tr><td>#'.$f['id'].'</td><td>'.e($f['fuel_date']).'</td><td>'.num($f['liters'],3).'</td><td>$'.num($f['amount']).'</td><td>•••• '.e($f['card_last4']).'</td><td><div class="actions">'.linkButton('Editar','fuel',['id'=>$f['id'],'trip_id'=>$id],'secondary small');deleteForm('fuel_delete',(int)$f['id'],'¿Eliminar esta carga de gasolina?',['trip_id'=>$id,'version'=>$f['version']]);echo '</div></td></tr>';}
 if(!$fuels)echo '<tr><td colspan="6" class="empty">Esta bitácora no tiene cargas. Puedes agregarlas en cualquier momento.</td></tr>';else echo '<tr class="total"><td colspan="2">Total de la bitácora</td><td>'.num(array_sum(array_column($fuels,'liters')),3).'</td><td>$'.num(array_sum(array_column($fuels,'amount'))).'</td><td colspan="2"></td></tr>';echo '</tbody></table></div></section><div class="actions">'.linkButton('Volver al panel','dashboard',[],'secondary');deleteForm('trip_delete',$id,'¿Eliminar la bitácora #'.$id.' y TODAS sus cargas de gasolina?',['version'=>$t['version']]);echo '</div>';
}
function fuelView(): void {$id=(int)($_GET['id']??0);$old=$id?need('fuel_loads',$id):[];$tid=(int)($old['trip_id']??$_GET['trip_id']??0);$trip=need('trips',$tid);$v=$_SERVER['REQUEST_METHOD']==='POST'?$_POST:$old;pageTitle($id?'Editar carga #'.$id:'Nueva carga de gasolina','Bitácora #'.$tid.' · '.$trip['driver'],linkButton('Volver','trip',['id'=>$tid],'secondary'));echo '<form method="post" class="panel">'.csrf();hidden('action','fuel_save');hidden('id',$id);hidden('trip_id',$tid);hidden('version',$v['version']??1);warningBox();echo '<div class="form-grid">';fuelFields($v);echo '</div><p class="help">El importe es el total pagado por esta carga. Se sumará al mes de la fecha de carga, aunque la captures después.</p><button class="button">Guardar carga</button></form>';}
function periodView(): void {$id=(int)($_GET['id']??0);$old=$id?need('inactive_periods',$id):[];$vid=(int)($old['vehicle_id']??$_GET['vehicle_id']??0);$vehicle=need('vehicles',$vid);$v=$_SERVER['REQUEST_METHOD']==='POST'?$_POST:$old;pageTitle($id?'Editar periodo #'.$id:'Nuevo periodo de inactividad',$vehicle['economic_number'].' · '.$vehicle['brand'].' '.$vehicle['model'],linkButton('Volver','vehicle',['id'=>$vid],'secondary'));echo '<form method="post" class="panel">'.csrf();hidden('action','period_save');hidden('id',$id);hidden('vehicle_id',$vid);hidden('version',$v['version']??1);warningBox();echo '<div class="form-grid">';inputField('start_date','Inactivo desde (incluido)',$v['start_date']??date('Y-m-d'),'date','required');inputField('end_date','Inactivo hasta (incluido; opcional)',$v['end_date']??'','date');echo '<label class="field"><span>Estado</span><select name="reason">';foreach(['Descompuesto','En servicio','No disponible'] as $s)echo '<option '.(($v['reason']??'')===$s?'selected':'').'>'.e($s).'</option>';echo '</select></label>';inputField('notes','Notas',$v['notes']??'','text','maxlength="500"');echo '</div><p class="help">Deja el fin vacío mientras siga inactivo. Para volver a estar disponible hoy, el último día de inactividad debe ser ayer. Un periodo de un solo día usa la misma fecha de inicio y fin.</p><button class="button">Guardar periodo</button></form>';}
function reportsView(): void {
 $month=(string)($_GET['month']??date('Y-m'));[$a,$b]=monthBounds($month);$vid=(int)($_GET['vehicle_id']??0);pageTitle('Concentrados','Consulta mensual de recorridos, gasolina e inactividad.');
 echo '<section class="panel"><form method="get" class="filter-form">';hidden('page','reports');inputField('month','Mes',$month,'month','required');vehicleSelect($vid,true);echo '<button class="button">Consultar</button></form><div class="actions export-actions">'.linkButton('Excel general','export',['kind'=>'general','month'=>$month],'secondary');if($vid)echo linkButton('Excel del vehículo','export',['kind'=>'vehicle','month'=>$month,'vehicle_id'=>$vid]);echo linkButton('Exportar todos los registros','export',['kind'=>'data'],'secondary').'</div><p class="help">Recorridos: mes de salida. Gasolina: fecha de carga. El Excel individual incluye todos los días del mes y marca sábados y domingos en rojo.</p></section>';
 $vs=$vid?[need('vehicles',$vid)]:rows('SELECT * FROM vehicles ORDER BY economic_number');$totKm=0;$totL=0;$totA=0;
 echo '<section class="panel"><div class="section-heading"><h2>Resumen · '.e($month).'</h2><span>'.count($vs).' vehículos</span></div><div class="table-wrap"><table><thead><tr><th>Vehículo</th><th>Km inicio</th><th>Km cierre</th><th>Km registrados</th><th>Diferencia odómetro</th><th>Litros</th><th>Total MXN</th><th>Detalle</th></tr></thead><tbody>';
 foreach($vs as $v){$s=monthSummary($v,$month);$totKm+=$s['km'];$totL+=$s['liters'];$totA+=$s['amount'];echo '<tr><td><strong>'.e($v['economic_number']).'</strong><small>'.e($v['brand'].' '.$v['model'].' · '.$v['plates']).'</small></td><td>'.num($s['initial']).'<small>'.e($s['source']).'</small></td><td>'.num($s['final']).'<small>'.($s['count']?'Último registro del mes':'Sin recorridos registrados').'</small></td><td>'.num($s['km']).'</td><td>'.num($s['odometer']).'</td><td>'.num($s['liters'],3).'</td><td>$'.num($s['amount']).'</td><td>'.linkButton('Ver mes','reports',['month'=>$month,'vehicle_id'=>$v['id']],'secondary small').'</td></tr>';}
 echo '<tr class="total"><td colspan="3">Totales registrados</td><td>'.num($totKm).'</td><td>—</td><td>'.num($totL,3).'</td><td>$'.num($totA).'</td><td></td></tr></tbody></table></div><p class="help">Km registrados = suma de recorridos. Diferencia de odómetro = cierre − inicio; puede diferir si faltan bitácoras o existen superposiciones. Las lecturas corresponden a los datos disponibles, no certifican un cierre completo.</p></section>';
 if($vid){$v=$vs[0];$s=monthSummary($v,$month);echo '<section class="panel"><h2>Bitácoras del mes</h2>';tripTable(array_map(fn($t)=>$t+['economic_number'=>$v['economic_number'],'plates'=>$v['plates']],$s['trips']));echo '</section>';}
 echo '<section class="panel"><h2>Inactividad durante el mes</h2><div class="table-wrap"><table><thead><tr><th>Vehículo</th><th>Estado</th><th>Inicio</th><th>Fin</th><th>Notas</th></tr></thead><tbody>';$n=0;foreach($vs as $v)foreach(rows('SELECT * FROM inactive_periods WHERE vehicle_id=? AND start_date<? AND (end_date IS NULL OR end_date>=?) ORDER BY start_date',[$v['id'],$b,$a]) as $p){$n++;echo '<tr><td>'.e($v['economic_number']).'</td><td>'.e($p['reason']).'</td><td>'.e($p['start_date']).'</td><td>'.e($p['end_date']??'Sin fecha de fin').'</td><td>'.e($p['notes']).'</td></tr>';}if(!$n)echo '<tr><td colspan="5" class="empty">No hay periodos de inactividad en este mes.</td></tr>';echo '</tbody></table></div></section>';
}
function gapsView(): void {
 $from=(string)($_GET['from']??date('Y-m'));$to=(string)($_GET['to']??$from);[$start]=monthBounds($from);[, $end]=monthBounds($to);if($end<=$start||((int)substr($to,0,4)-(int)substr($from,0,4))*12+(int)substr($to,5,2)-(int)substr($from,5,2)>35)throw new RuntimeException('Selecciona un rango de hasta 36 meses en orden cronológico.');$vid=(int)($_GET['vehicle_id']??0);
 pageTitle('Kilómetros pendientes','Huecos detectados entre lecturas conocidas, incluso entre meses.');echo '<section class="panel"><form method="get" class="filter-form">';hidden('page','gaps');inputField('from','Desde',$from,'month','required');inputField('to','Hasta',$to,'month','required');vehicleSelect($vid,true);echo '<button class="button">Consultar</button></form></section><div class="notice info">Un hueco entre meses se muestra en los meses que abarca, pero no se reparte: falta la fecha exacta del recorrido. Si no existe una lectura posterior, el tramo final no puede calcularse.</div>';
 $vs=$vid?[need('vehicles',$vid)]:rows('SELECT * FROM vehicles ORDER BY economic_number');echo '<section class="panel table-wrap"><table><thead><tr><th>Vehículo</th><th>Mes</th><th>Estado</th><th>Rango km</th><th>Km del rango</th><th>Entre registros</th><th>Observación</th></tr></thead><tbody>';
 foreach($vs as $v){$all=rows('SELECT * FROM trips WHERE vehicle_id=? ORDER BY departure_at,id',[$v['id']]);for($m=$start;$m<$end;$m=date('Y-m-d',strtotime($m.' +1 month'))){$month=substr($m,0,7);$gaps=missingRanges($v,$all,$month);foreach($gaps as $g){echo '<tr><td>'.e($v['economic_number']).'<small>'.e($v['plates']).'</small></td><td>'.e($month).'</td><td><span class="badge '.($g['type']==='Faltante'?'amber':'red').'">'.e($g['type']).'</span></td><td>'.num($g['from']).' → '.num($g['to']).'</td><td>'.num($g['km']).'</td><td>'.e($g['before'].' → '.$g['after']).'<small>'.e($g['dates']).'</small></td><td>'.($g['uncertain']?'Abarca varios meses. No asignable a un mes exacto.':'Rango entre lecturas del mismo mes.').'</td></tr>';}
  $nextMonth=date('Y-m-d',strtotime($m.' +1 month'));$later=array_filter($all,fn($t)=>$t['departure_at']>=$nextMonth);$in=array_filter($all,fn($t)=>$t['departure_at']>=$m&&$t['departure_at']<$nextMonth);
  if(!$gaps||!$later){$msg=!$all?'Sin lecturas de bitácoras; no se puede determinar un cierre.':(!$later?'Cierre no comprobable: falta una lectura posterior al mes.':(!$in?'Sin bitácoras este mes; verifica si el vehículo se utilizó.':'Sin huecos detectados entre los registros conocidos.'));echo '<tr><td>'.e($v['economic_number']).'<small>'.e($v['plates']).'</small></td><td>'.e($month).'</td><td><span class="badge neutral">'.(!$later?'Por comprobar':'Sin hueco detectado').'</span></td><td>—</td><td>—</td><td>—</td><td>'.e($msg).'</td></tr>';}
 }}if(!$vs)echo '<tr><td colspan="7" class="empty">Registra vehículos para comenzar.</td></tr>';echo '</tbody></table></section>';
}
function importView(): void {
 global $importPreview;$importPreview??=$_SESSION['import_review']??null;
 pageTitle('Importar registros','Agrega bitácoras históricas o cargas posteriores desde Excel.',linkButton('Descargar plantilla','export',['kind'=>'template'],'secondary'));
 echo '<section class="panel"><h2>1. Selecciona tu archivo</h2><p>Crea primero los vehículos. Usa el número económico para identificarlos en la hoja <strong>Bitacoras</strong>. La hoja <strong>Cargas</strong> permite varias cargas por bitácora.</p><form method="post" enctype="multipart/form-data" class="upload-form">'.csrf();hidden('action','import_preview');inputField('xlsx','Archivo XLSX','','file','required accept=".xlsx"');echo '<button class="button">Revisar archivo</button></form><p class="help">La plantilla usa una sola fecha de solicitud para la salida y la llegada; conserva ambas horas. Máximo 8 MB y 2000 filas por hoja. No cambies los encabezados. Las claves existentes se omiten si sus datos son idénticos; los cambios se realizan desde la aplicación.</p></section>';
 if($importPreview){echo '<section class="panel"><h2>2. Revisa y confirma</h2><div class="stats compact"><div><span>Bitácoras nuevas</span><strong>'.$importPreview['trips'].'</strong></div><div><span>Cargas nuevas</span><strong>'.$importPreview['fuel'].'</strong></div><div><span>Idénticos a omitir</span><strong>'.$importPreview['skipped'].'</strong></div></div><form method="post">'.csrf();hidden('action','import_commit');if($importPreview['warnings']){echo '<div class="notice warning"><strong>'.count($importPreview['warnings']).' advertencia(s)</strong><div class="warning-scroll"><ul>';foreach($importPreview['warnings'] as $w)echo '<li>'.e($w).'</li>';echo '</ul></div><label class="check"><input type="checkbox" name="accept_import" value="1" required> He revisado las advertencias y deseo importar.</label></div>';}else echo '<p>No se detectaron advertencias.</p>';echo '<button class="button">Confirmar importación</button></form><p class="help">Se guarda todo el archivo en una sola operación. Si hay un error, no se guarda parcialmente.</p></section>';}
}

function reservationsView(): void {
    pageTitle('Programación', 'Vehículos apartados por fecha y hora.', linkButton('+ Apartar vehículo', 'reservation_form'));
    $vehicle = (int)($_GET['vehicle_id'] ?? 0);
    $date = trim((string)($_GET['date'] ?? ''));
    if ($date !== '') dateValue($date, 'Fecha de consulta');
    echo '<section class="panel"><form method="get" class="filter-form">';
    hidden('page', 'reservations');vehicleSelect($vehicle, true);inputField('date', 'Fecha programada', $date, 'date');
    echo '<button class="button">Consultar</button><a class="button secondary" href="'.e(url('reservations')).'">Ver todos</a></form></section>';
    $where = [];$params = [];
    if ($vehicle) {$where[] = 'r.vehicle_id=?';$params[] = $vehicle;}
    if ($date !== '') {$where[] = 'r.scheduled_at>=? AND r.scheduled_at<?';$params[] = $date;$params[] = date('Y-m-d', strtotime($date.' +1 day'));}
    $from = ' FROM reservations r JOIN vehicles v ON v.id=r.vehicle_id'.($where ? ' WHERE '.implode(' AND ', $where) : '');
    $count = (int)row('SELECT COUNT(*) n'.$from, $params)['n'];
    $pages = max(1, (int)ceil($count / 25));$page = max(1, min((int)($_GET['p'] ?? 1), $pages));
    $appointments = rows('SELECT r.*,v.economic_number,v.brand,v.model,v.plates'.$from.' ORDER BY r.scheduled_at,r.id LIMIT 25 OFFSET '.(($page-1)*25), $params);
    echo '<section class="panel"><div class="section-heading"><h2>Vehículos apartados</h2><span>'.$count.' apartado(s)</span></div><div class="table-wrap"><table class="schedule-table"><thead><tr><th>Vehículo</th><th>Fecha programada</th><th>Hora</th><th>Acciones</th></tr></thead><tbody>';
    foreach ($appointments as $r) {
        echo '<tr><td><strong>'.e($r['economic_number'].' · '.$r['brand'].' '.$r['model']).'</strong><small>'.e($r['plates']).'</small></td><td>'.e(substr($r['scheduled_at'],0,10)).'</td><td>'.e(substr($r['scheduled_at'],11,5)).'</td><td><div class="actions">'.linkButton('Editar / mover', 'reservation_form', ['id'=>$r['id']], 'secondary small');
        deleteForm('reservation_cancel', (int)$r['id'], '¿Cancelar este apartado? Se quitará de la programación.', ['version'=>$r['version']], 'Cancelar apartado');
        echo '</div></td></tr>';
    }
    if (!$appointments) echo '<tr><td colspan="4" class="empty">No hay vehículos apartados para esta consulta.</td></tr>';
    echo '</tbody></table></div><div class="pagination"><span>Página '.$page.' de '.$pages.'</span><div>';
    $filter = ['vehicle_id'=>$vehicle,'date'=>$date];
    if ($page > 1) echo linkButton('Anterior','reservations',$filter+['p'=>$page-1],'secondary small');
    if ($page < $pages) echo linkButton('Siguiente','reservations',$filter+['p'=>$page+1],'secondary small');
    echo '</div></div><p class="help">Puedes mover un apartado o cancelarlo cuando cambie la solicitud. Los apartados permanecen en esta tabla hasta que los canceles; el recorrido realizado se registra por separado en Bitácoras.</p></section>';
}
function reservationFormView(): void {
    $id = (int)($_GET['id'] ?? 0);
    $old = $id ? need('reservations', $id) : [];
    $values = $old;
    if ($old) {
        $values['scheduled_date'] = substr($old['scheduled_at'], 0, 10);
        $values['scheduled_time'] = substr($old['scheduled_at'], 11, 5);
    }
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'reservation_save') $values = $_POST;
    pageTitle($id ? 'Editar apartado' : 'Apartar vehículo', 'Indica el vehículo, día y hora de la solicitud.', linkButton('Volver', 'reservations', [], 'secondary'));
    echo '<form method="post" class="panel">'.csrf();
    hidden('action','reservation_save');hidden('id',$id);hidden('version',$values['version'] ?? 1);
    echo '<div class="form-grid">';vehicleSelect($values['vehicle_id'] ?? 0);
    inputField('scheduled_date','Fecha programada',$values['scheduled_date'] ?? date('Y-m-d'),'date','required');
    inputField('scheduled_time','Hora programada',$values['scheduled_time'] ?? '','time','required');
    echo '</div><p class="help">Esta agenda es informativa. Al realizar el préstamo, captura su bitácora desde el panel de vehículos.</p><button class="button">'.($id ? 'Guardar cambios' : 'Guardar apartado').'</button></form>';
}
